# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='soil',
        ),
        migrations.AddField(
            model_name='zone',
            name='trees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
